### ISSUE TITLE
How I convert '0x77359400'

### ISSUE THREAD

**Issue by amandiobm** [mbezhanov/ethereum-converter#1]
Hey, I'm trying to use your converter, but my API return `0x77359400` as value. How can I convert this to wei?

King regards.

**Comment by amandiobm** [comment]
I'm testing some codes that I found then I'll create a PR.

**Comment by mbezhanov** [comment]
Hello @amandiobm,

Would a method with a signature similar to this one work for you: https://web3js.readthedocs.io/en/1.0/web3-utils.html#hextonumber

Also, can you please paste a sample response from the API you are using, so I can put this into context?

**Comment by amandiobm** [comment]
Basically the API return `"0x4e0fb2f17db64ac00"`. I manage to convert using this approach.

```
private function decodeHex($input)
{
    if (substr($input, 0, 2) == '0x') {
        $input = substr($input, 2);
    }

    if (preg_match('/[a-f0-9]+/', $input)) {
        return hexdec($input);
    }

    return $input;
}
```
So that value is equal to
`ETH 89.998579358`
`Wei 89998579358000000000`

**Comment by mbezhanov** [comment]
I would advise against using PHP's built-in `hexdec()` function to perform the conversion from hex to decimal, as PHP will represent the larger numbers as `float` internally, and you will very likely encounter floating-point arithmetic errors.

I'd recommend using a safe arithmetic library such as https://github.com/krowinski/bcmath-extended to avoid such errors. There is a PR currently open (https://github.com/krowinski/bcmath-extended/pull/25) which calls for adding `hexdec()` and `dechex()` functions into the library. While the PR is still pending, consider using your own custom function, that you can define like this:

```php
<?php

require 'vendor/autoload.php';

use BCMathExtended\BC;

function bchexdec($hex) {
    $remainingDigits = substr($hex, 0, -1);
    $lastDigitToDecimal = \hexdec(substr($hex, -1));

    if (strlen($remainingDigits) === 0) {
        return $lastDigitToDecimal;
    }

    return BC::add(BC::mul(16, bchexdec($remainingDigits)), $lastDigitToDecimal, 0);
}

$valueInWei = '0x4e0fb2f17db64ac00';

echo hexdec($valueInWei);
// output is: 8.9998579358E+19

echo bchexdec($valueInWei);
// output is: 89998579358000000000

```

And to illustrate the potential floating-point arithmetic problems with your current approach, consider the following example:

```php
$firstValueInWei = '0x4e0fb2f17db64ac00';
$secondValueInWei = '0x0ea1277359400abcd';

// Using PHP's built-in hexdec() function and performing an arithmetic operation:
// ===========================================
echo hexdec($firstValueInWei);
// output is: 8.9998579358E+19

echo hexdec($secondValueInWei);
// output is: 1.6866674626456E+19

echo hexdec($firstValueInWei) + hexdec($secondValueInWei);
// output is: 1.0686525398446E+20

echo BC::convertScientificNotationToString(1.0686525398446E+20);
// output is: 106865253984460000000

// Using BCMath library and your custom function
// ===========================================
echo bchexdec($firstValueInWei);
// output is: 89998579358000000000

echo bchexdec($secondValueInWei);
// output is: 16866674626455972813

echo BC::add(bchexdec($firstValueInWei), bchexdec($secondValueInWei));
// output is: 106865253984455972813
```

As you can see, in the first example, your value is off by `4027187` Wei!

**Comment by mbezhanov** [comment]
@amandiobm https://github.com/krowinski/bcmath-extended/pull/25 was accepted, and  https://github.com/krowinski/bcmath-extended now includes the `hexdec()` and `dechex()` functions, so you can just use:

```php
<?php

require 'vendor/autoload.php';

use Bezhanov\Ethereum\Converter;
use BCMathExtended\BC;

$valueInWei = '0x4e0fb2f17db64ac00';
$converter = new Bezhanov\Ethereum\Converter();
$valueInEther = $converter->fromWei(BC::hexdec($valueInWei), 'ether');

printf('%s Wei is %s Ether', $valueInWei, $valueInEther);
// outputs: "0x4e0fb2f17db64ac00 Wei is 89.9985793580000000000000000000000000000 Ether"
```

**Comment by mbezhanov** [comment]
@amandiobm PR https://github.com/krowinski/bcmath-extended/pull/25 was accepted, and  https://github.com/krowinski/bcmath-extended now includes the `hexdec()` and `dechex()` functions out of the box, so you can just use:

```php
<?php

require 'vendor/autoload.php';

use Bezhanov\Ethereum\Converter;
use BCMathExtended\BC;

$valueInWei = BC::hexdec('0x4e0fb2f17db64ac00');
$converter = new Bezhanov\Ethereum\Converter();
$valueInEther = $converter->fromWei($valueInWei, 'ether');

printf('%s Wei is %s Ether', $valueInWei, $valueInEther);
// outputs: "89998579358000000000 Wei is 89.9985793580000000000000000000000000000 Ether"
```

**Comment by amandiobm** [comment]
@mbezhanov tks buddy, I installed and works perfectly.

**Comment by martianatwork** [comment]
For anyone who is having issue with much bigger value.
try to remove starting 0x from the string.

it works perfectly.
